import { useMemo, useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { BarChart3, Boxes, CheckCircle2, ChevronRight, CircleUserRound, Copy, ExternalLink, FileArchive, LayoutDashboard, Link2, LogOut, Plus, Search, Settings2, ShieldCheck, Sparkles, UsersRound } from "lucide-react";

const fmt = (value: unknown) => value ? new Date(Number(value)).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" }) : "—";
const nav = [{ key:"dashboard", label:"Dashboard", icon:LayoutDashboard }, { key:"qrs", label:"QR Codes", icon:Boxes }, { key:"customers", label:"Clientes", icon:UsersRound }, { key:"batch", label:"Gerar Lote", icon:FileArchive }, { key:"settings", label:"Configurações", icon:Settings2 }];
function Button({ children, onClick, kind="primary", type="button" }: any) { return <button type={type} onClick={onClick} className={`btn ${kind}`}>{children}</button>; }
function Stat({ label, value, accent }: any) { return <div className="stat"><div className={`stat-icon ${accent}`}><Sparkles size={18}/></div><div><span>{label}</span><strong>{value ?? 0}</strong></div></div>; }

export default function Home() {
  const { user, loading, logout } = useAuth(); const [section, setSection] = useState("dashboard"); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [toast, setToast] = useState("");
  const dashboard = trpc.admin.dashboard.useQuery(undefined, { enabled: Boolean(user?.role === "admin") });
  const qrs = trpc.admin.qrs.useQuery({ search, status }, { enabled: Boolean(user?.role === "admin") });
  const customers = trpc.admin.customers.useQuery({ search }, { enabled: Boolean(user?.role === "admin") });
  const batches = trpc.admin.createBatch.useMutation({ onSuccess: data => { setToast(`Lote criado com ${data.items.length} QR Codes.`); qrs.refetch(); dashboard.refetch(); } });
  const createCustomer = trpc.admin.createCustomer.useMutation({ onSuccess: () => { setToast("Cliente criado."); customers.refetch(); setSection("customers"); } });
  const assignQr = trpc.admin.assignQr.useMutation({ onSuccess: () => { setToast("QR ativado e associado ao cliente."); qrs.refetch(); dashboard.refetch(); } });
  const saveLink = trpc.admin.saveLink.useMutation({ onSuccess: () => setToast("Link salvo na landing page.") });
  const [batchQty, setBatchQty] = useState(20); const [serial, setSerial] = useState(1); const [customer, setCustomer] = useState({ businessName:"", phone:"", city:"", state:"", googleReviewUrl:"" });
  const [activation, setActivation] = useState({ qrId: 0, customerId: 0, mode: "GOOGLE_REVIEW", destinationUrl: "" });
  const [linkDraft, setLinkDraft] = useState({ customerId: 0, type: "SITE", label: "Site", value: "", icon: "link", position: 0, enabled: true });
  const activeNav = useMemo(() => nav.find(item => item.key === section) ?? nav[0], [section]);
  if (loading) return <div className="loading-screen"><div className="brand-mark">RSA</div><p>Carregando painel seguro…</p></div>;
  if (!user) return <div className="login-screen"><div className="login-card"><div className="brand-mark">RSA</div><p className="eyebrow">CONTROLE DE QR CODES</p><h1>Um destino. <em>Infinitas possibilidades.</em></h1><p className="muted">Gerencie placas, clientes e páginas públicas com URLs permanentes da RSA Digital.</p><Button onClick={() => startLogin()}>Entrar como administrador <ChevronRight size={18}/></Button></div></div>;
  if (user.role !== "admin") return <div className="login-screen"><div className="login-card"><ShieldCheck size={42} color="#e0a82e"/><h1>Acesso restrito</h1><p className="muted">Sua conta está autenticada, mas não possui perfil de administrador.</p><Button kind="ghost" onClick={logout}><LogOut size={16}/> Sair</Button></div></div>;
  const cards = dashboard.data?.cards as any;
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark small">RSA</div><div><b>RSA Digital</b><span>QR Control</span></div></div><div className="workspace"><span>WORKSPACE</span><strong>Operação principal</strong></div><nav>{nav.map(item => <button key={item.key} className={section===item.key?"active":""} onClick={() => setSection(item.key)}><item.icon size={18}/>{item.label}</button>)}</nav><div className="sidebar-bottom"><div className="user-chip"><CircleUserRound size={20}/><div><b>{user.name || "Administrador"}</b><span>{user.email || "conta principal"}</span></div></div><button className="logout" onClick={logout}><LogOut size={16}/> Sair</button></div></aside><main className="main"><header className="topbar"><div><span className="eyebrow">{activeNav.label.toUpperCase()}</span><h2>{section === "dashboard" ? "Visão geral da operação" : activeNav.label}</h2></div><div className="top-actions"><div className="secure"><ShieldCheck size={15}/> Sessão protegida</div><Button onClick={() => setSection("batch")}><Plus size={16}/> Novo lote</Button></div></header>{toast && <div className="toast" onClick={() => setToast("")}><CheckCircle2 size={18}/>{toast}</div>}
{section === "dashboard" && <section><div className="hero"><div><span className="eyebrow">BOM DIA, ADMINISTRADOR</span><h1>Seu inventário, em um só lugar.</h1><p>Acompanhe os códigos permanentes que mantêm cada experiência conectada.</p></div><div className="hero-art"><div className="hero-stars">★ ★ ★ ★ ★</div><span>GO · LANDING · NFC</span></div></div><div className="stats-grid"><Stat label="QR Codes totais" value={cards?.total} accent="blue"/><Stat label="Ativos" value={cards?.active} accent="green"/><Stat label="Em estoque" value={cards?.stock} accent="amber"/><Stat label="Clientes" value={cards?.customers} accent="purple"/></div><div className="dashboard-grid"><div className="panel wide"><div className="panel-head"><div><span className="eyebrow">ATIVIDADE RECENTE</span><h3>Últimos movimentos</h3></div><Button kind="ghost" onClick={() => setSection("qrs")}>Ver QR Codes <ChevronRight size={15}/></Button></div><div className="activity-list">{dashboard.data?.recent?.length ? dashboard.data.recent.map((item:any) => <div className="activity" key={item.id}><div className="activity-dot"/><div><b>{item.action.replaceAll("_", " ")}</b><span>{item.business_name || item.entity_type} · {fmt(item.created_at)}</span></div><span className="activity-code">{item.serial_number ? `#${String(item.serial_number).padStart(6,"0")}` : "AUDIT"}</span></div>) : <div className="empty"><BarChart3 size={28}/><p>Nenhuma atividade registrada ainda.</p></div>}</div></div><div className="panel"><span className="eyebrow">LEITURAS</span><h3>Alcance dos códigos</h3><div className="reach"><strong>{cards?.scansToday ?? 0}</strong><span>scans hoje</span></div><div className="reach"><strong>{cards?.scans30 ?? 0}</strong><span>últimos 30 dias</span></div><div className="mini-note"><Link2 size={16}/> Destinos sempre editáveis, QR nunca substituído.</div></div></div></section>}
{section === "qrs" && <section className="content-section"><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Buscar por empresa, telefone, número ou public code" value={search} onChange={e=>setSearch(e.target.value)}/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos os status</option><option value="STOCK">Estoque</option><option value="RESERVED">Reservados</option><option value="ACTIVE">Ativos</option><option value="INACTIVE">Inativos</option></select></div><div className="panel table-panel"><div className="panel-head"><div><span className="eyebrow">INVENTÁRIO PERMANENTE</span><h3>{qrs.data?.length ?? 0} códigos encontrados</h3></div><Button onClick={() => setSection("batch")}><Plus size={16}/> Gerar lote</Button></div><div className="table-wrap"><table><thead><tr><th>Número</th><th>Public code</th><th>Cliente</th><th>Modo</th><th>Status</th><th>Scans</th><th>Último acesso</th><th/></tr></thead><tbody>{qrs.data?.map((qr:any)=><tr key={qr.id}><td><b>#{String(qr.serial_number).padStart(6,"0")}</b></td><td><code>{qr.public_code}</code></td><td>{qr.business_name || <span className="muted">Disponível em estoque</span>}</td><td><span className="mode">{qr.mode === "LANDING_PAGE" ? "Landing page" : "Google review"}</span></td><td><span className={`pill ${qr.status.toLowerCase()}`}>{qr.status}</span></td><td>{qr.scan_count}</td><td>{fmt(qr.last_scan_at)}</td><td><div style={{display:"flex",gap:8,alignItems:"center"}}>{qr.status === "STOCK" && <button className="icon-link" onClick={()=>setActivation({qrId:qr.id,customerId:customers.data?.[0]?.id ?? 0,mode:"GOOGLE_REVIEW",destinationUrl:""})}>Ativar</button>}<a className="icon-link" href={`https://go.rsadigitalconsultoria.com.br/${qr.public_code}`} target="_blank"><ExternalLink size={16}/></a></div></td></tr>)}</tbody></table>{!qrs.data?.length && <div className="empty"><Boxes size={30}/><p>Gere seu primeiro lote para começar.</p></div>}</div></div></section>}
 {activation.qrId > 0 && <section className="panel activation-panel"><div className="panel-head"><div><span className="eyebrow">ATIVAÇÃO</span><h3>Associar QR ao cliente</h3></div><button className="icon-link" onClick={()=>setActivation({qrId:0,customerId:0,mode:"GOOGLE_REVIEW",destinationUrl:""})}>Fechar</button></div><div className="form-grid"><label>Cliente<select value={activation.customerId} onChange={e=>setActivation({...activation,customerId:Number(e.target.value)})}>{customers.data?.map((item:any)=><option key={item.id} value={item.id}>{item.business_name}</option>)}</select></label><label>Modo<select value={activation.mode} onChange={e=>setActivation({...activation,mode:e.target.value})}><option value="GOOGLE_REVIEW">Google Review</option><option value="LANDING_PAGE">Landing page</option></select></label><label className="full">Destino adicional (landing page)<input value={activation.destinationUrl} onChange={e=>setActivation({...activation,destinationUrl:e.target.value})} placeholder="https://..."/></label><Button onClick={()=>assignQr.mutate({...activation,mode:activation.mode as "GOOGLE_REVIEW"|"LANDING_PAGE"})}><CheckCircle2 size={16}/> Ativar QR</Button></div></section>}
 {section === "customers" && <section className="content-section"><div className="split"><div className="panel"><div className="panel-head"><div><span className="eyebrow">CADASTRO RÁPIDO</span><h3>Novo cliente</h3></div><CircleUserRound size={28} color="#82aef2"/></div><form className="form-grid" onSubmit={e=>{e.preventDefault();createCustomer.mutate({...customer, state:customer.state.toUpperCase()})}}><label>Empresa<input required value={customer.businessName} onChange={e=>setCustomer({...customer,businessName:e.target.value})} placeholder="Padaria São João"/></label><label>Telefone<input value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})} placeholder="(13) 99999-9999"/></label><label>Cidade<input value={customer.city} onChange={e=>setCustomer({...customer,city:e.target.value})} placeholder="Guarujá"/></label><label>Estado<input maxLength={2} value={customer.state} onChange={e=>setCustomer({...customer,state:e.target.value})} placeholder="SP"/></label><label className="full">Google Review URL<div style={{display:"flex",gap:8}}><input value={customer.googleReviewUrl} onChange={e=>setCustomer({...customer,googleReviewUrl:e.target.value})} placeholder="Cole a URL direta fornecida pelo Google"/><Button kind="ghost" type="button" onClick={()=>customer.googleReviewUrl && window.open(customer.googleReviewUrl,"_blank","noopener,noreferrer")}><ExternalLink size={14}/> Testar link</Button></div></label><Button type="submit"><Plus size={16}/> Criar cliente</Button></form></div><div className="panel"><div className="panel-head"><div><span className="eyebrow">BASE DE CLIENTES</span><h3>Clientes cadastrados</h3></div><div className="count-badge">{customers.data?.length ?? 0}</div></div><div className="customer-list">{customers.data?.map((item:any)=><div className="customer-row" key={item.id}><div className="avatar">{item.business_name.slice(0,1).toUpperCase()}</div><div><b>{item.business_name}</b><span>{item.phone || "Sem telefone"} · {item.city || "Cidade não informada"}/{item.state || "—"}</span></div><ChevronRight size={16}/></div>)}</div></div></div></section>}
{section === "customers" && <section className="panel link-editor"><div className="panel-head"><div><span className="eyebrow">LANDING PAGE</span><h3>Adicionar link público</h3></div><Link2 size={25} color="#82aef2"/></div><div className="form-grid"><label>Cliente<select value={linkDraft.customerId} onChange={e=>setLinkDraft({...linkDraft,customerId:Number(e.target.value)})}><option value={0}>Selecione</option>{customers.data?.map((item:any)=><option key={item.id} value={item.id}>{item.business_name}</option>)}</select></label><label>Tipo<select value={linkDraft.type} onChange={e=>setLinkDraft({...linkDraft,type:e.target.value})}><option value="SITE">Site</option><option value="INSTAGRAM">Instagram</option><option value="WHATSAPP">WhatsApp</option><option value="PIX">Chave Pix</option><option value="WIFI">Wi-Fi</option><option value="GOOGLE_REVIEW">Avaliar no Google</option></select></label><label>Nome do botão<input value={linkDraft.label} onChange={e=>setLinkDraft({...linkDraft,label:e.target.value})}/></label><label>URL ou conteúdo<input value={linkDraft.value} onChange={e=>setLinkDraft({...linkDraft,value:e.target.value})} placeholder="https://..."/></label><Button onClick={()=>saveLink.mutate(linkDraft)}><Plus size={16}/> Salvar link</Button></div></section>}
{section === "batch" && <section className="content-section"><div className="batch-layout"><div className="panel batch-form"><span className="eyebrow">PRODUÇÃO DE PLACAS</span><h3>Gerar novo lote</h3><p className="muted">Crie códigos não sequenciais, permanentes e prontos para receber a arte física.</p><label>Quantidade<input type="number" min="1" max="500" value={batchQty} onChange={e=>setBatchQty(Number(e.target.value))}/></label><label>Número inicial<input type="number" min="1" value={serial} onChange={e=>setSerial(Number(e.target.value))}/></label><div className="batch-preview"><div className="preview-stars">★ ★ ★ ★ ★</div><b>CONECTE-SE<br/><strong>CONOSCO</strong></b><span>QR + NFC · ARTE PADRÃO</span></div><Button onClick={()=>batches.mutate({quantity:batchQty,startingSerial:serial})}><FileArchive size={16}/> Gerar lote e manifest</Button></div><div className="panel"><span className="eyebrow">CHECKLIST DE INTEGRIDADE</span><h3>Antes do download</h3><ul className="checklist"><li><CheckCircle2/> Unicidade do public code</li><li><CheckCircle2/> Correspondência serial ↔ QR</li><li><CheckCircle2/> URL própria permanente</li><li><CheckCircle2/> SVG individual em alta qualidade</li><li><CheckCircle2/> ZIP pronto para produção</li></ul><div className="callout"><Copy size={18}/><div><b>A arte nunca aponta para um destino externo.</b><span>O QR usa go.rsadigitalconsultoria.com.br e o painel decide o destino atual.</span></div></div></div></div></section>}
{section === "settings" && <section className="content-section"><div className="panel settings-panel"><span className="eyebrow">CONFIGURAÇÕES</span><h3>Domínios e integrações</h3><div className="setting-row"><div><b>URL pública</b><span>go.rsadigitalconsultoria.com.br</span></div><span className="pill active">Preparado</span></div><div className="setting-row"><div><b>Painel administrativo</b><span>app.rsadigitalconsultoria.com.br</span></div><span className="pill active">Preparado</span></div><div className="setting-row"><div><b>Banco de dados</b><span>Turso / libSQL — server-side</span></div><span className="pill active">Conectado</span></div><div className="setting-row"><div><b>Google Review URL</b><span>Administrador cola e testa o link manualmente</span></div><span className="pill active">Sem API</span></div><div className="callout"><Settings2 size={18}/><div><b>Segurança por padrão</b><span>Secrets ficam no backend. Nenhum acesso público altera dados.</span></div></div></div></section>}
</main></div>;
}
